extras  ::=  { /\s/ }

externals  ::=  { _automatic_semicolon 'else' }

conflits  ::=  { { foo bar } }

rules:
  top1  ::=  foo | blah | bar | buzz | ok | low
  foo  ::=  'hello'
  blah  ::=  ('blah' | 'barz' | (foo 'x'))+
  bar  ::=  'bar' ((foo foo): blah)
  buzz  ::=  'car' ((foo foo) -> car)
  ok  ::=  @('ok' 'go')
  low  ::=  !(/[a-z]+/ 'ok')
  zz  ::=  /[a-z]+/ (',' /[a-z]+/)*
  _zz  ::=  'zzzzzaaa'
  ww  ::=  'zzz' (zz: top) 'kk'
  anno  ::=  >('@' (_zz: name) (ok*: arguments))
  function_definition  ::=  'foo' (('=' (_zz: body)) | (zz: body))
  pc  ::=  -1('kk' _zz)
